name: MEGSI_ITI
services:
    megsi-config-server-fs:
        container_name: megsi-config-server
        networks:
            - megsi-net
        ports:
            - 8888:8888
        volumes:
            - /srv/configuration-server-fs:/srv/configuration-server-fs
        image: rafaelrpsantos/megsi-config-server-fs:latest
        healthcheck:
          test: ["CMD-SHELL", "wget -qO- http://localhost:8888/actuator/health | grep -q '\"status\":\"UP\"'"]
          interval: 10s
          timeout: 5s
          retries: 12
          start_period: 30s

    megsi-autenticator:
        container_name: megsi-autenticador
        networks:
            - megsi-net
        ports:
            - 30000:8080
        environment:
            - SPRING_CLOUD_CONFIG_URI=http://megsi-config-server:8888
            - MARIADB_SERVER_URI=mariadb
            - MYSQL_ROOT_PASSWORD=uminho
            - KAFKA_SERVER_URI=kafka:29092
            - EMAIL_PASSWORD=awhxghptidnaprkw
        image: rafaelrpsantos/megsi-autenticator:latest
        depends_on:
            megsi-config-server-fs:
                condition: service_healthy

    megsi-autoscaler:
      image: rafaelrpsantos/megsi-iti-autoscaler:latest
      container_name: megsi-autoscaler
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      cpus: "0.5"
      mem_limit: 256M
      networks:
        - megsi-net
      environment:
        - RPS_UP=5
        
#.   Este serviço será iniciado pelo script dentro do container megsi-autoscaler
#    megsi-iti-service-files:
#      container_name: megsi-iti-service-files-1
#      image: rafaelrpsantos/megsi-iti-service-files:latest
#      networks:
#        - megsi-net
#        - traefik-net
#      environment:
#        - SPRING_CLOUD_CONFIG_URI=http://megsi-config-server:8888
#        - MARIADB_SERVER_URI=mariadb
#        - MYSQL_ROOT_PASSWORD=uminho
#        - KAFKA_SERVER_URI=kafka:29092
#      volumes:
#        - /Users/rafaelrolimprudentedossantos/work/studies/mestrado/ITI/UMDRIVEFILES:/mnt/NAS
#      labels:
#        - "traefik.enable=true"
#        - "traefik.http.routers.files.rule=Host(`files.localhost`)"
#        - "traefik.http.routers.files.entrypoints=web"
#        - "traefik.http.services.files.loadbalancer.server.port=8081"

networks:
  megsi-net:
    external: true
    name: megsi-net
