apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.56.103
    path: /mnt/PODS/MARIADB

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: uminho
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mariadb-pv
  storageClassName: ""

---

apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: uminho
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "uminho"

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: uminho
spec:
  clusterIP: None
  selector:
    app: mariadb
  ports:
  - port: 3306
    name: mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: uminho
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql

        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e "SELECT 1"
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e "SELECT 1"
          initialDelaySeconds: 30
          periodSeconds: 15

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mariadb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb-external
  namespace: uminho
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
